HAI 1.3

CAN HAS STDIO?

I HAS A RADWIMPS ITZ A BUKKIT

HOW IZ RADWIMPS then YR safics
  FOUND YR SMOOSH "前" AN safics MKAY
IF U SAY SO

HOW IZ RADWIMPS se
  FOUND YR "世"
IF U SAY SO

VISIBLE I IZ RADWIMPS'Z then YR I IZ RADWIMPS'Z then YR I IZ RADWIMPS'Z then YR I IZ RADWIMPS'Z se MKAY MKAY MKAY MKAY

KTHXBYE
